### ISSUE TITLE
How to handle loss and draw conditions with only checkWinConditions?

### ISSUE THREAD

**Issue by ericvrp** [panchishin/alphabeta#3]
I am working on a game that ends when all squares on a board have been filled. Each player much fill a square whenever it is his turn.
The player wil the most squares of his color is the winner. Equal amounts of occupied squares indicate a draw. How should I handle this with this package?

**Comment by ericvrp** [comment]
To answer my own question and closing this issue: The tictactoe example shows how to do this.

**Comment by panchishin** [comment]
thanks!
